stages:
  - Build
  - Deploy
 
before_script:
  - version=`cat version`
 
variables:
  ALIYUN_REGISTRY: registry-vpc.cn-hangzhou.aliyuncs.com
  REGISTRY_NAME_SPECE: nfc
  IMAGE_FULL_NAME: $ALIYUN_REGISTRY/$REGISTRY_NAME_SPECE/$CI_PROJECT_NAME

################################################### 测试环境 #######################################################
Build dev:
  stage: Build
  script:
    - pnpm i --registry=http://npm.ycb51.cn
    - pnpm run staging
    - docker build -t $IMAGE_FULL_NAME:dev .
    - docker push $IMAGE_FULL_NAME:dev
    - echo $IMAGE_FULL_NAME:dev
  only:
    refs:
      - test
  except:
    changes:
      - .gitlab-ci.yml
  tags:
    - ci
 
deploy dev:
  stage: Deploy
  script:
    - kubectl replace --force -f /root/helm_repo/supplychain/operate_admin_page_v3/dev-deployment.yml
  only:
    refs:
      - test
  except:
    changes:
      - .gitlab-ci.yml
  tags:
    - kube-master1-test


################################################### 预发布环境 #######################################################
Build uat:
  stage: Build
  script:
    - pnpm i --registry=http://npm.ycb51.cn
    - pnpm run build
    - docker build -t $IMAGE_FULL_NAME:uat .
    - docker push $IMAGE_FULL_NAME:uat
    - echo $IMAGE_FULL_NAME:uat
  only:
    refs:
      - uat
  except:
    changes:
      - .gitlab-ci.yml
  tags:
    - ci
  
deploy uat:
  stage: Deploy
  script:
    - kubectl replace --force -f /root/helm_repo/supplychain/operate_admin_page_v3/uat-deployment.yml
  only:
    refs:
      - uat
  except:
    changes:
      - .gitlab-ci.yml
  tags:
    - kube-master1-test
  when: manual


################################################### 生产环境 #######################################################
Build prod:
  stage: Build
  script:
    - pnpm i --registry=http://npm.ycb51.cn
    - pnpm run build
    - docker build -t $IMAGE_FULL_NAME:prod .
    - docker push $IMAGE_FULL_NAME:prod
    - echo $IMAGE_FULL_NAME:prod
  only:
    refs:
      - master
  except:
    changes:
      - .gitlab-ci.yml
  tags:
    - ci
  
deploy prod:
  stage: Deploy
  script:
    - kubectl replace --force -f /root/helm_repo/supplychain/operate_admin_page_v3/prod-deployment.yml
  only:
    refs:
      - master
  except:
    changes:
      - .gitlab-ci.yml
  tags:
    - kube-master1-test
  when: manual
