apiVersion: v1
kind: Service
metadata:
  name: operation-platform-nodeport
  namespace: apps
spec:
  selector:
    app: operation-platform
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
  type: NodePort
