server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /api_platform/;
  }

  location /api_platform/ {
    try_files $uri $uri/ /api_platform/index.html;
  }

  location /open-platform/ {
    proxy_pass https://supply-test.ycb51.cn;
    proxy_ssl_server_name on;
    proxy_set_header Host supply-test.ycb51.cn;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /transfer-v2/ {
    proxy_pass https://supply-test.ycb51.cn;
    proxy_ssl_server_name on;
    proxy_set_header Host supply-test.ycb51.cn;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /assets/ {
    proxy_pass https://supply-test.ycb51.cn;
    proxy_ssl_server_name on;
    proxy_set_header Host supply-test.ycb51.cn;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
